<?php

    function cards_menu() {
      $friends = array('Vlad', 'Dave', 'Jess');
      $items = array();
        foreach ($friends as $friend) {
            $items[$friend] = array(
                'title' => $friend,
                'page callback' => 'greet_friend',
                'access callback' => TRUE,
                'type' => MENU_NORMAL_ITEM,
            );
        }
        return $items;
    }

    function greet_friend() {
         $url1 = "this is " . arg(0);
         return $url1;
    }
