<?php

    function sum_menu() {
        $items = array();
        $items['sum'] = array(
            'title' => 'Calculate Sum',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('sum_form'), //this will tell drupal that whehn the sum url is visited, the drupal_get_form function will run with the argument sum_form, sum_form is the name of the function that drupal will call to build the form
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
        );

        $items['success'] = array(
            'title' => 'Success',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'sum_success',
        );
        return $items;
    }

    function sum_form() {
        $form['left_number'] = array(
            '#title' => 'Left Number',
            '#type' => 'textfield',
            '#description' => t('Please enter your starting number'),
            '#element_validate' => array('element_validate_number', 'element_validate_range', 'element_validate_even'),
            '#required' => TRUE,
        );

        $form['right_number'] = array(
            '#title' => 'Right Number',
            '#type' => 'textfield',
            '#description' => t('Please enter a number to add to your starting number'),
            '#element_validate' => array('element_validate_number', 'element_validate_range', 'element_validate_even'),
            '#required' => TRUE,
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Calculate Sum',
        );

        return $form;
    }

    function element_validate_range($element) {
      if ($element['#value'] >50 || $element['#value'] < -50) {
        form_error($element, t('Number must be less than 50 or greater than -50.'));
      }
    }

    function element_validate_even($element) {
      if ($element['#value'] % 2 != 0) {
        form_error($element, t('Number must be even'));
      }
    }

    function sum_form_submit($form, &$form_state) {
        $first_number = $form_state['values']['left_number'];
        $second_number = $form_state['values']['right_number'];
        $sum = $first_number + $second_number;
        $_SESSION['sum_output'] = $sum;
        $form_state['redirect'] = 'success';
    }

    function sum_success() {
        $answer = $_SESSION['sum_output'];
        return "you've calculated a sum! The answer is $answer";
    }
