<?php

    function sum_menu() {
        $items = array();
        $items['sum'] = array(
            'title' => 'Calculate Sum',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('sum_form'), //this will tell drupal that whehn the sum url is visited, the drupal_get_form function will run with the argument sum_form, sum_form is the name of the function that drupal will call to build the form
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
        );

        $items['success'] = array(
            'title' => 'Success',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'sum_success',
        );
        return $items;
    }

    function sum_form() {
        $form['left_number'] = array(
            '#title' => 'Left Number',
            '#type' => 'textfield',
            '#description' => t('Please enter your starting number'),
        );

        $form['right_number'] = array(
            '#title' => 'Right Number',
            '#type' => 'textfield',
            '#description' => t('Please enter a number to add to your starting number'),
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Calculate Sum',
        );

        return $form;
    }

    function sum_form_submit($form, &$form_state) {
        $first_number = $form_state['values']['left_number'];
        $second_number = $form_state['values']['right_number'];
        $sum = $first_number + $second_number;
        $_SESSION['sum_output'] = $sum;
        $form_state['redirect'] = 'success';
    }

    function sum_success() {
        $answer = $_SESSION['sum_output'];
        return "you've calculated a sum! The answer is $answer";
    }
