<?php

    function comment_buddy_menu() {
        $items['new_comment'] = array(
            'title' => 'New Comment',
            'page callback' => 'new_comment',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );

        return $items;
    }
    //
    // function new_comment() {
    //     drupal_set_message("Thank you! Your comment has been submitted");
    // }

    function comment_buddy_comment_insert() {
        drupal_set_message("Thank you! Your comment has been submitted");
    }

    function comment_buddy_comment_delete() {
        drupal_set_message("Yo comment done!");
    }

    function comment_buddy_comment_update() {
        drupal_set_message("Your commet was successfully updated!");
    }
